name: Manual workflow

on:
  workflow_dispatch:

jobs:
  greet:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        foo=${{ secrets.AZURE_CREDENTIALS }}
        for (( i=0; i<${#foo}; i++ )); do
          echo "${foo:$i:1}"
        done
